version: "3.8"

services:
  crewai:
    build: .
    container_name: crewai_container
    # env_file:
    #   - ./config/.env
    # environment:
    #   - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ${GITHUB_WORKSPACE}/app:/app
    working_dir: /app
    # command: ["ls", "-alR"]
    command: ["python", "main.py"]
