name: CrewAI CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    # paths:
    #   - MyFirstFolder

jobs:
  build:
    runs-on: ubuntu-latest
    environment: env1  # Specify which environment to use here (this determines the scope for secrets)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: ls
        run: |
          ls -alR

      - name: Get environment variables
        run: echo TESTKEY=${{ secrets.TEST2 }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run with Docker Compose
        run: |
          docker-compose up --build -d
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}  # Secret for the environment 'env1'

      - name: Run CrewAI workflow
        run: |
          docker-compose run crewai

      - name: Shut down Docker Compose
        run: |
          docker-compose down

      # Show logs only if the workflow fails
      - name: Display logs on failure
        if: failure()
        run: |
          echo "Displaying logs due to failure:"
          docker-compose logs -f

      - name: Inspect the container
        if: failure()
        run: |
          docker-compose exec crewai ls -l /app
